# SPDX-FileCopyrightText: 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

"""
Data Models for TCH Orchestrator 

Define the structure of configuration, targets, results, and progress events
throughout the TCH Orchestrator workflow execution.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Callable, List, Optional

# ======================================================================
# Public API
# ======================================================================
__all__ = [
    "Target",
    "DeploymentTopologyType",
    "StageHandler",
    "ORCHESTRATION_STAGES",
    "StageStatus",
    "StageResult",
    "StageProgress",
    "OrchestratorConfig",
    "OrchestratorResult",
]

# ======================================================================
# Topology and Target Configuration
# ======================================================================

class DeploymentTopologyType(str, Enum):
    """Supported deployment topology strategy types."""
    SINGLE_LOCAL = "local"              # Host running on localhost, Single DUT 
    B2B          = "back-to-back"       # Host running on Talker, Two DUTs (Talker/Listener) with direct connection between them. Coordination of execution across both DUTs shall be done through different NIC. 
    MULTI_DUT    = "multi-dut"          # Dedicated Host, Many DUTs

@dataclass
class Target: 
    """DUT target connection information for orchestration."""
    id: str                             # Unique identifier for the target
    ip_address: str                     # IP address of the target. For local mode, it can be 127.0.0.1
    role: Optional[str] = None          # Internally assigned based on topology detection (e.g., "talker", "listener"). For SINGLE_LOCAL, role will be None.
    ssh_user: Optional[str] = None      # SSH username for remote connection (None for local mode)
    ssh_password: Optional[str] = None  # SSH password for remote connection (if not using key-based auth)
    ssh_key_path: Optional[str] = None  # Path to SSH private key for authentication (if not using password)
    ssh_port: int = 22                  # SSH port (default is 22)

    @property
    def sc_target_id(self) -> Optional[str]:
        """Return the system_controller identity string, or None for local targets."""
        if self.ssh_user is None:
            return None
        return f"{self.ssh_user}@{self.ip_address}"

    def __post_init__(self):
        # SSH credential validation only applies when ssh_user is set (remote targets)
        if self.ssh_user:
            if self.ssh_password and self.ssh_key_path:
                raise ValueError(f"Target '{self.id}': ssh_password and ssh_key_path are mutually exclusive. Provide one, not both.")
            if not self.ssh_password and not self.ssh_key_path:
                raise ValueError(f"Target '{self.id}': one of ssh_password or ssh_key_path must be provided.")

# ======================================================================
# Orchestration Execution Pipeline
# ======================================================================

# Type alias for a stage handler callable
StageHandler = Callable[["Target", bool], List[str]]

ORCHESTRATION_STAGES = (
    "install",              # install necessary tools and dependencies on targets (Testnench, AI Workloads)
    "apply_config",         # apply TCC and TSN configurations on targets
    "run",                  # execute the defined workflow (e.g., start TCC, run test workloads)
    "results",              # collect results, logs, and any relevant data from targets after workflow execution
)

class StageStatus(Enum):
    """Execution status for workflow stages."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"

@dataclass
class StageResult:
    """Represents the result of executing a workflow stage."""
    target_id: str                      # ID of the target associated with this stage result
    success: bool                       # Indicates if the stage executed successfully
    output: List[str]                   # Output or logs generated by the stage
    duration_ms: Optional[int] = None   # Duration of stage execution in milliseconds

@dataclass
class StageProgress: 
    """Represents the progress of a workflow stage."""
    target_id: str                                  # ID of the target reporting progress
    stage_name: str                                 # Name of the stage
    status: StageStatus                             # Current execution status of the stage
    progress_percentage: Optional[float] = None     # Optional percentage completion for long-running stages
    message: Optional[str] = None                   # Optional message providing additional context about the stage progress


# ======================================================================
# Orchestration Request Interface and Result
# ======================================================================

@dataclass
class OrchestratorConfig:
    """Configuration for the Orchestrator."""
    topology_type: DeploymentTopologyType  # Deployment topology strategy to use
    targets: List[Target]                  # List of deployment targets (DUTs)
    tcc_config: str                        # TCC config file path 
    tsn_config: str                        # TSN config file path
    stages_to_run: List[str]               # List of stages to execute in the workflow
    dry_run: bool = False                  # If true, simulate execution without performing actual operations
    test_duration: Optional[int] = None    # Optional expected duration of the test in seconds (for progress reporting)
    timeout: Optional[int] = None          # Optional maximum allowed duration for the entire workflow in seconds (for timeout handling)
    # TODO: Plugins configuration (AI workload and validation plugins)

    def __post_init__(self):
        invalid = set(self.stages_to_run) - set(ORCHESTRATION_STAGES)
        if invalid:
            raise ValueError(f"Unknown stages: {sorted(invalid)}. Valid stages: {list(ORCHESTRATION_STAGES)}")

        # Enforce pipeline ordering: stages must appear in ORCHESTRATION_STAGES order
        indices = [ORCHESTRATION_STAGES.index(s) for s in self.stages_to_run]
        if indices != sorted(indices):
            raise ValueError(
                f"Stages must follow pipeline order {list(ORCHESTRATION_STAGES)}. "
                f"Got: {self.stages_to_run}"
            )

@dataclass
class OrchestratorResult:
    """Result returned by the Orchestrator after workflow execution."""
    success: bool                          # True if all stages completed without error
    logs: List[str]                        # Informational log messages from the workflow
    errors: List[str]                      # Error messages if any stage failed

